[project]
name = "l1-support-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rodion Chikibaev", email = "r.chikibaev@innopolis.university" }
]
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "mcp[cli]>=2.0.0",
    "pytest>=9.1.1",
]

[project.scripts]
l1-support-agent = "l1_support_agent:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.16.2",
]
